language: c++

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
      env:
            - MATRIX_EVAL=CXX=g++
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
      env:
            - MATRIX_EVAL=clang++-6.0

notifications:
  email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq cppcheck qt5-default qtbase5-dev lcov

script:
- cppcheck --quiet --error-exitcode=1 .
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$MATRIX_EVAL .. && make -j4
- cd src
- ./travis_test
- cd ../test
- ./example_test
- cd ..
- make coverage
 
