language: c++

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7.4.0
      env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
      env:
            - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

notifications:
  email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq cppcheck qt5-default qtbase5-dev lcov

script:
- cppcheck --quiet --error-exitcode=1 .
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Coverage .. && make -j4
- cd src
- ./travis_test
- cd ../test
- ./example_test
- cd ..
- make coverage
